### ISSUE TITLE
How the dataset is preprocessed

### ISSUE THREAD

**Issue by yqtian-se** [LASER-UMASS/Themis#27]
Hi, I am trying to reproduce the result in FSE 2017. I find that the dataset locates at ESEC.FSE.2017.Experimental.Replication/Figure1/datasets/Census. However, it seems these data have been preprocessed somehow. 

May I know how did you preprocess the data? Or are they copied from other paper/repo?

Thanks for your help!

**Comment by sainyam** [comment]
Hi,

We encoded all categorical variables as numerical values 0-D-1, if the column has D unique values. For continuous variables and large D, we binned the values. This was done due to our assumption that the input characteristics and the output characteristic are categorical variables.

Hope this helps.

**Comment by yqtian-se** [comment]
Hi,

I see. How do you handle the missing cell? How is the width of each bin decided?

Thanks.

**Comment by sainyam** [comment]
Hi

I am not sure if I remember the exact details. Missing values were encoded as different categorical value. The exact bin width depended on the range of column values but I am not sure of the exact value used.

**Comment by yqtian-se** [comment]
Hi, 

Thanks! I will have a try.
